const products = [
  {
    name: 'Red Apple',
    type: 'fruit',
    description: 'Crisp red apples with a sweet finish.',
    price: 120,
    image: 'https://images.unsplash.com/photo-1567306226416-28f0efdc88ce',
    stock: 60,
    category: 'Pome',
    unit: 'kg',
    featured: true,
  },
  {
    name: 'Green Apple',
    type: 'fruit',
    description: 'Tart green apples great for salads.',
    price: 110,
    image: 'https://images.unsplash.com/photo-1459411621453-7b03977f4bfc',
    stock: 55,
    category: 'Pome',
    unit: 'kg',
  },
  {
    name: 'Banana',
    type: 'fruit',
    description: 'Naturally sweet bananas, ripe and soft.',
    price: 90,
    image: 'https://images.unsplash.com/photo-1574226516831-e1dff420e43e',
    stock: 80,
    category: 'Tropical',
    unit: 'kg',
  },
  {
    name: 'Orange',
    type: 'fruit',
    description: 'Juicy oranges packed with vitamin C.',
    price: 130,
    image: 'https://images.unsplash.com/photo-1547514701-42782101795e',
    stock: 70,
    category: 'Citrus',
    unit: 'kg',
    featured: true,
  },
  {
    name: 'Strawberry',
    type: 'fruit',
    description: 'Sweet strawberries with bright aroma.',
    price: 260,
    image: 'https://images.unsplash.com/photo-1464965911861-746a04b4bca6',
    stock: 35,
    category: 'Berry',
    unit: 'kg',
  },
  {
    name: 'Blueberry',
    type: 'fruit',
    description: 'Plump blueberries, perfect for smoothies.',
    price: 320,
    image: 'https://images.unsplash.com/photo-1464965911861-746a04b4bca6',
    stock: 28,
    category: 'Berry',
    unit: 'kg',
  },
  {
    name: 'Mango',
    type: 'fruit',
    description: 'Tropical mangoes with rich, sweet flavor.',
    price: 220,
    image: 'https://images.unsplash.com/photo-1528825871115-3581a5387919',
    stock: 45,
    category: 'Tropical',
    unit: 'kg',
  },
  {
    name: 'Pineapple',
    type: 'fruit',
    description: 'Fresh pineapple with bright acidity.',
    price: 180,
    image: 'https://images.unsplash.com/photo-1502741338009-cac2772e18bc',
    stock: 25,
    category: 'Tropical',
    unit: 'kg',
  },
  {
    name: 'Watermelon',
    type: 'fruit',
    description: 'Refreshing watermelon, sweet and crisp.',
    price: 150,
    image: 'https://images.unsplash.com/photo-1567306226416-28f0efdc88ce',
    stock: 40,
    category: 'Melon',
    unit: 'kg',
  },
  {
    name: 'Grapes',
    type: 'fruit',
    description: 'Seedless grapes with a clean finish.',
    price: 200,
    image: 'https://images.unsplash.com/photo-1519996529931-28324d5a630e',
    stock: 50,
    category: 'Berry',
    unit: 'kg',
    featured: true,
  },
  {
    name: 'Carrot',
    type: 'vegetable',
    description: 'Crunchy carrots rich in beta carotene.',
    price: 80,
    image: 'https://images.unsplash.com/photo-1447175008436-054170c2e979',
    stock: 90,
    category: 'Root',
    unit: 'kg',
  },
  {
    name: 'Potato',
    type: 'vegetable',
    description: 'Starchy potatoes, versatile and filling.',
    price: 70,
    image: 'https://images.unsplash.com/photo-1447175008436-054170c2e979',
    stock: 100,
    category: 'Root',
    unit: 'kg',
  },
  {
    name: 'Tomato',
    type: 'vegetable',
    description: 'Vine tomatoes with balanced sweetness.',
    price: 95,
    image: 'https://images.unsplash.com/photo-1546470427-e31f2a2b91a9',
    stock: 75,
    category: 'Nightshade',
    unit: 'kg',
    featured: true,
  },
  {
    name: 'Cucumber',
    type: 'vegetable',
    description: 'Cool cucumbers for salads and snacks.',
    price: 85,
    image: 'https://images.unsplash.com/photo-1447175008436-054170c2e979',
    stock: 65,
    category: 'Gourd',
    unit: 'kg',
  },
  {
    name: 'Spinach',
    type: 'vegetable',
    description: 'Fresh spinach leaves, tender and green.',
    price: 90,
    image: 'https://images.unsplash.com/photo-1506806732259-39c2d0268443',
    stock: 40,
    category: 'Leafy',
    unit: 'kg',
  },
  {
    name: 'Lettuce',
    type: 'vegetable',
    description: 'Crisp lettuce for light meals.',
    price: 75,
    image: 'https://images.unsplash.com/photo-1506806732259-39c2d0268443',
    stock: 55,
    category: 'Leafy',
    unit: 'kg',
  },
  {
    name: 'Broccoli',
    type: 'vegetable',
    description: 'Broccoli florets, rich in fiber.',
    price: 140,
    image: 'https://images.unsplash.com/photo-1459411621453-7b03977f4bfc',
    stock: 48,
    category: 'Cruciferous',
    unit: 'kg',
  },
  {
    name: 'Cauliflower',
    type: 'vegetable',
    description: 'Mild cauliflower, great for roasting.',
    price: 150,
    image: 'https://images.unsplash.com/photo-1459411621453-7b03977f4bfc',
    stock: 38,
    category: 'Cruciferous',
    unit: 'kg',
  },
  {
    name: 'Bell Pepper',
    type: 'vegetable',
    description: 'Colorful bell peppers, sweet and crisp.',
    price: 170,
    image: 'https://images.unsplash.com/photo-1502741338009-cac2772e18bc',
    stock: 42,
    category: 'Nightshade',
    unit: 'kg',
  },
  {
    name: 'Onion',
    type: 'vegetable',
    description: 'Yellow onions with strong aroma.',
    price: 60,
    image: 'https://images.unsplash.com/photo-1506806732259-39c2d0268443',
    stock: 85,
    category: 'Allium',
    unit: 'kg',
  },
];

module.exports = products;
